#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#define QUICK_TAP_TERM_PER_KEY
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define DEBOUNCE 10
#define NO_ACTION_ONESHOT